name: Build and Deploy Python App to Azure Web App - UnifiedGymManager

on:
  push:
    branches:
      - master  # Trigger on pushes to the 'master' branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      # Step 4: Create ZIP Package
      - name: Create ZIP package
        run: |
          cd backend  # Navigate into the backend directory
          zip -r ../app.zip . -x "*.git*" -x "*venv*"  # Create app.zip at the root

      # Step 5: Debugging - List Files
      - name: Debugging - List files
        run: ls -la

      # Step 6: Upload Artifact for Deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download Artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app

      # Step 2: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unifiedgymmanager'  # Name of your Azure Web App
          package: './app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
