name: Build and deploy Python app to Azure Web App - unifiedgymmanager

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv backend/venv
          source backend/venv/bin/activate

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests (Optional but Recommended)
        run: |
          cd backend
          source venv/bin/activate
          python manage.py test  # Update with your testing framework if needed

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip ../release.zip ./* -r -x "venv/*" "*.git*" "*.github*" "__pycache__/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'unifiedgymmanager'
          package: './'  # Ensure the deployment package is the unzipped folder
